services:
  - type: web
    name: weather-oracle-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_WEATHER_ORACLE_ADDRESS
        sync: true
      - key: REACT_APP_SUBGRAPH_URI
        sync: true
