services:
  - type: static
    name: weather-oracle-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/build
    envVars:
      - key: REACT_APP_WEATHER_ORACLE_ADDRESS
        sync: false
      - key: REACT_APP_SUBGRAPH_URI
        sync: false
